### ISSUE TITLE
Traceback if a package appears in more than one repo

### ISSUE THREAD

**Issue by stefanhusmann** [polygamma/aurman#12]
I get this:
[haawda@frege blis]$ LANG=C aurman -Suy
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 xyne-x86_64 is up to date
 my is up to date
:: Starting full system upgrade...
 there is nothing to do

analyzing installed packages...
fetching upstream repo packages...
2018-02-25 13:06:03,193 - classes - append_packages - ERROR - Package reflector-2017.11-1 already known
2018-02-25 13:06:03,194 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 281, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 140, in process
    upstream_system = System(System.get_repo_packages())
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 823, in __init__
    self.append_packages(packages)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 834, in append_packages
    raise InvalidInput("Package {} already known".format(package))
aurman.own_exceptions.InvalidInput: Package reflector-2017.11-1 already known

reflectore is in [community]  and in [xyne-any].

**Comment by polygamma** [comment]
fixed in: https://github.com/polygamma/aurman/commit/71882673c8867af1116984a61f55cf2484f3bcf9
