### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 81: ordinal not in range(128)

### ISSUE THREAD

**Issue by FlashDaggerX** [polygamma/aurman#146]
The main script throws this every time I attempt an upgrade. Am I missing a dependency?

Trace:

`2018-06-09 18:44:48,219 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 666, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 591, in process
    package.show_pkgbuild(noedit, show_changes, pgp_fetch, keyserver, always_edit, default_show_changes)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1043, in show_pkgbuild
    self.search_and_fetch_pgp_keys(fetch_always, keyserver)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 914, in search_and_fetch_pgp_keys
    pgp_keys = Package.getPGPKeys(os.path.join(package_dir, "PKGBUILD"))
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 214, in getPGPKeys
    pkgbuild_content: str = f.read().strip()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
`

**Comment by polygamma** [comment]
no useful information given. issue template is not available for fun

**Comment by polygamma** [comment]
nevertheless: see issue 88, will most likely be your problem

**Comment by polygamma** [comment]
Have you read and understood Issue 88?

**Comment by Shub1427** [comment]
I did,  and updated my locale as well. My current session locale was updated, but changes weren't system wide I guess. Restarting the system made the locale settings proper, and it worked.

Will remember to restart the desktop before posting next time. :+1:

**Comment by polygamma** [comment]
Well, why do think it's sensible NOT to mention which locale you have actually set?

**Comment by eli-schwartz** [comment]
It doesn't really matter whether the description is in English, using broken locales is broken.

Also if you literally used the locale "en_US" that's pretty incorrect too.

Also if you try setting a locale which you have not actually configured in locale-gen, that won't work.

Also locales are not an aurman bug.

**Comment by realKennyStrawn93** [comment]
Changed the locale back to the default. It's still throwing the error when trying to update VirtualBox.

**Comment by polygamma** [comment]
Cool, that you are still not mentioning what **exactly** you are doing.
