### ISSUE TITLE
Permission error during upgrade on idna

### ISSUE THREAD

**Issue by jsaalfeld** [polygamma/aurman#148]
## Description
I update my my laptop 1-2 a week. Had it updated last tuesday and wanted to update again today. It failed on my during the upgrade with aurman of aurman itself.

## Expected Behavior
Normal upgrade from 2.9.39.r1.gc7394d5-1  ->  2.10.r2.g4af71e6-1

## Current Behavior
```
:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                       [###########################] 100%
(1/1) checking package integrity                     [###########################] 100%
(1/1) loading package files                          [###########################] 100%
(1/1) checking for file conflicts                    [###########################] 100%
(2/2) checking available disk space                  [###########################] 100%
:: Processing package changes...
(1/1) removing expac                                 [###########################] 100%
(1/1) installing expac-git                           [###########################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
==> Making package: aurman-git 2.10.r2.g4af71e6-1 (Mon 11 Jun 2018 08:58:53 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating aurman_sources git repo...
Fetching origin
remote: Counting objects: 112, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 112 (delta 64), reused 58 (delta 10), pack-reused 0
Receiving objects: 100% (112/112), 48.74 KiB | 332.00 KiB/s, done.
Resolving deltas: 100% (64/64), completed with 1 local object.
From https://github.com/polygamma/aurman
   c7394d5..20dc675  develop    -> develop
   c7394d5..20dc675  master     -> master
 * [new tag]         2.10       -> 2.10
==> Validating source files with md5sums...
    aurman_sources ... Skipped
==> Extracting sources...
  -> Creating working copy of aurman_sources git repo...
Cloning into 'aurman_sources'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Updated version: aurman-git 2.10.r17.g20dc675-1
==> Entering fakeroot environment...
==> Starting package()...
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from setuptools import setup, find_packages
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/lib/python3.6/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3079, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in _build_master
    ws = cls()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 554, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 610, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1958, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2028, in distributions_from_metadata
    root, entry, metadata, precedence=DEVELOP_DIST,
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2467, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2842, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2431, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2621, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1404, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1400, in get_metadata
    value = self._get(self._fn(self.egg_info, name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1512, in _get
    with open(path, 'rb') as stream:
PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/idna-2.7-py3.6.egg-info/PKG-INFO'
==> ERROR: A failure occurred in package().
    Aborting...
```

Then i ran the update command as sudo to get a sophisticated error message and recieved:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 888, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (idna 2.7 (/usr/lib/python3.6/site-packages), Requirement.parse('idna<2.7,>=2.5'), {'requests'})
```

## Possible Solution
Solved it by removing aurman from the aurman cache and installing systemwide the required ```idna``` version requested system-wide via

    sudo pip install 'idna<2.7,>=2.5'

## Version of aurman you are using
Was ```2.9.39.r1.gc7394d5-1``` is now ```2.10.r17.g20dc675-1```

## Steps to Reproduce

1. Have idna not installed systemwide or idna in version 2.7
2. Have aurman installed in version 2.9.39.r1.gc7394d5-1
3. run ```aurman -Syu```

**Comment by polygamma** [comment]
https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/python-requests&id=0d436720a7a036de5854fbe898054208b69271f6

**Comment by polygamma** [comment]
I wrote an email to the maintainer of the "python-requests" package, if he could include the correct versioned dependencies in the PKGBUILD of "python-requests" so that stuff does not break after a simple "pacman -Syu".
