### ISSUE TITLE
Python error when installing ruby-acme-client

### ISSUE THREAD

**Issue by Arthapz** [polygamma/aurman#154]
Hi,

## Description
When i try to install ruby-acme-client like this 
`aurman -S ruby-acme-client` i get python3 errors

## Expected Behavior
ruby-acme-client installed on my computer

## Current Behavior
python3 error:

```shell
> aurman -S ruby-acme-client
~~ initializing aurman...
~~ the following packages are neither in known repos nor in the aur
:: js-24.2.0-4
~~ calculating solutions...

:: The following 5 package(s) are getting installed:
   extra/ruby                     /  ->  2.5.1-1
   aur/ruby-acme-client           /  ->  0.5.0-1
   community/ruby-faraday         /  ->  0.15.2-1
   community/ruby-multipart-post  /  ->  2.0.0-2
   extra/rubygems                 /  ->  2.7.7-1

?? Do you want to continue? Y/n: 
~~ looking for new pkgbuilds and fetching them...
?? Do you want to see the changes of ruby-acme-client? N/y: 
2018-06-13 10:15:53,228 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 734, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 646, in process
    package.show_pkgbuild(noedit, show_changes, pgp_fetch, keyserver, always_edit, default_show_changes)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1051, in show_pkgbuild
    self.search_and_fetch_pgp_keys(fetch_always, keyserver)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 922, in search_and_fetch_pgp_keys
    pgp_keys = Package.getPGPKeys(os.path.join(package_dir, "PKGBUILD"))
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 214, in getPGPKeys
    pkgbuild_content: str = f.read().strip()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 83: ordinal not in range(128)
```

## Version of aurman you are using
```shell
aurman -V
:: 2.11.r0.ga7b61c1-1
```

## Steps to Reproduce
1. aurman -S ruby-acme-client

## Read the README
Yes

**Comment by polygamma** [comment]
So, what's written in the README regarding your problem, does not fix it?

**Comment by polygamma** [comment]
Closing for now, because I am pretty sure, that the README simply has not been read properly.
