### ISSUE TITLE
ignore_arch fails for development packages in get_devel_version()

### ISSUE THREAD

**Issue by cryzed** [polygamma/aurman#159]
## Description
I read in the README that the `ignore_arch` setting in the `miscellaneous` section could be used to forward `--ignorearch` to makepkg, which in my understanding simply ignores the architectures in the PKGBUILD's `arch` array and attempts to build the package, even if the host uses a different architecture.

When I use aurman on my Raspberry Pi, using the Arch Linux ARM distribution, updating `aurman` started failing recently due to `armv7h` missing in `expac-git`'s PKGBUILD. Figuring I might run into these issues more often, I attempted specifying `ignore_arch`, however with no luck:

```
$ aurman -Syu --devel --needed
[...]
~~ initializing aurman...
~~ looking for new pkgbuilds of devel packages and fetching them...
==> ERROR: expac-git is not available for the 'armv7h' architecture.
2018-06-13 21:37:27,021 - wrappers - makepkg - ERROR - makepkg query makepkg -odc --noprepare --skipinteg failed in directory /home/user/.cache/aurman/expac-git
2018-06-13 21:37:27,022 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 675, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 515, in process
    package.get_devel_version()
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1099, in get_devel_version
    makepkg("-odc --noprepare --skipinteg", False, package_dir)
  File "/usr/lib/python3.6/site-packages/aurman/wrappers.py", line 144, in makepkg
    raise InvalidInput("makepkg query {} failed in directory {}".format(makepkg_query, dir_to_execute))
aurman.own_exceptions.InvalidInput: makepkg query makepkg -odc --noprepare --skipinteg failed in directory /home/user/.cache/aurman/expac-git
```

## Expected Behavior
The `arch` array in the PKGBUILD should be ignored and the build should be attempted.

## Current Behavior
The `arch` array in the PKGBUILD isn't ignored and the build fails immediately. I suspect this might only happen for development packages during the version check.

## Possible Solution
I think adding the `--noarch/-A` flag in the `makepkg("-odc --noprepare --skipinteg", False, package_dir)` call in `get_devel_version()`, depending on the user's aurman configuration, should fix the issue.

## Version of aurman you are using
:: 2.10-1

## Steps to Reproduce

1. Try to build a development package with an incompatible architecture, while having `ignore_arch` specified.

## Read the README
I did read the README.

**Comment by polygamma** [comment]
May you paste the content of your `aurman config`?

**Comment by cryzed** [comment]
It's just this:

```
[miscellaneous]
ignore_arch

```

**Comment by polygamma** [comment]
Ahhhhhhh, sorry, I read that wrong. It crashes at a point at which I never intended to include the use of `-A`. Going to push a fix in a few minutes, will let you know when I have done so.

**Comment by cryzed** [comment]
Thanks, awesome!

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/90030de1336b565cb649192244987a426d96495b

you may install `expac-git` and `aurman-git` manually, after that try `aurman -S --devel expac-git`, which should now succeed

**Comment by cryzed** [comment]
Thanks, I'll do that and report back!
