### ISSUE TITLE
Python exception

### ISSUE THREAD

**Issue by trulex** [polygamma/aurman#184]
THIS TEMPLATE IS FOR BUG REPORTS,
YOU DO NOT HAVE TO USE IT FOR FEATURE REQUESTS.

MAKE NEVERTHELESS SURE, THAT THE FEATURE REQUEST IS WORDED IN A MEANINGFUL WAY

## Description
Python exception is thrown after searching for a package

## Expected Behavior
No exception

## Current Behavior
Exception

## Possible Solution
No idea

## Version of aurman you are using
2.14-1

## Steps to Reproduce
1. aurman -Ss evolution
2. output:
```
extra/evolution 3.28.3-1 (gnome-extra) [installed]
    Manage your email, contacts and schedule
extra/evolution-bogofilter 3.28.3-1
    Spam filtering for Evolution, using Bogofilter
extra/evolution-data-server 3.28.3-1 [installed]
    Centralized access to appointments and contacts
extra/evolution-ews 3.28.3-1 [installed]
    MS Exchange integration through Exchange Web Services
extra/evolution-spamassassin 3.28.3-1
    Spam filtering for Evolution, using SpamAssassin
community/evolution-rss 0.3.95-4
    Plugin for Evolution Mail that enables reading of RSS/RDF/ATOM feeds
community/surfraw 2.3.0-2
    Shell Users' Revolutionary Front Rage Against the Web
aur/gnome-calendar-no-evolution 3.28.2-1 (2, 0.943639)
    Gnome's calender application, now featuring nearly 100% less unnecessary gnome evolution
aur/achilles 2_8-6 (4, 0.794652)
    An artificial life and evolution simulator that uses Hebbian neural networks and OpenGL/SDL to simulate life in a simplified environment. It is based on Larry Yaeger's PolyWorld idea
aur/r-tidyr 0.8.1-1 (1, 0.49857)
    An evolution of 'reshape2'. It's designed specifically for data tidying (not general reshaping or aggregating) and works well with 'dplyr' data pipelines.
aur/logisim-evolution 2.14.4-1 (1, 0.200314)
    An educational tool for designing and simulating digital logic circuits
aur/thrive 0.3.4-1 (2, 0.191815)
    Game about evolution, in which the player guides a species from their origin as a microbe to the space age and beyond.
aur/evolution-mapi 3.26.0-1 (24, 0.155561)
    MAPI plugin for evolution.
aur/pokemon-revolution-online-bin 0.98.4.1.mystical.lugia-1 (2, 0.073734)
2018-06-27 10:03:57,216 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 800, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 437, in process
    search_packages(pacman_args, packages_of_user_names, repo, aur)
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 238, in search_packages
    search_and_print(packages_of_user_names, installed_system, str(pacman_args), repo, aur)
  File "/usr/lib/python3.6/site-packages/aurman/utilities.py", line 113, in search_and_print
    print("    {}".format(ret_dict['Description']))
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 81: ordinal not in range(128)
```

## Read the README
I confirm

## Running linux distribution
arch

**Comment by polygamma** [comment]
you have been banned from the repository

**Comment by frealgagu** [comment]
Just for curiosity, why he has been banned from the repository?

**Comment by polygamma** [comment]
not reading the readme
