### ISSUE TITLE
.reviewed file not found

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#2]
It seems the `.reviewed` file is not created. 

```
$ python main.py -Su
:: Starting full system upgrade...
 there is nothing to do
AUR Packages: nlohmann-json auracle-git
Repo Packages:
Do you want to install these packages? Y/n: y
Do you want to view the changes of PKGBUILD of nlohmann-json ? N/y: y
Do you want to edit PKGBUILD? N/y: y
Do you want to use the files as they are now? Y/n: y
2018-02-08 10:15:29,733 - main - <module> - ERROR - Unknown exception occurred.
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    process(argv[1:])
  File "main.py", line 145, in process
    package.show_pkgbuild_install_files_to_user()
  File "/home/remy/code/aurman/src/package_classes.py", line 215, in show_pkgbuild_install_files_to_user
    with open(os.path.join(git_aurman_dir, ".reviewed"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/remy/.cache/aurman/auracle-git/.git/aurman/.reviewed'
```

**Comment by polygamma** [comment]
Hey, Remy!

Could you delete the .cache/aurman folder and try it again?
.reviewed file is being created with the first git clone currently, so if you had this package in the cache and updated the aurman version to the current release, this happens. Will be fixed nevertheless.

**Comment by rmarquis** [comment]
Yep, that fixed it, thanks. That explains why I got that error with some packages only.

**Comment by polygamma** [comment]
fixed in https://github.com/polygamma/aurman/commit/93b2f71230d7a94be25372778456a839a845afbd
