### ISSUE TITLE
failed on --noconfirm with no tty

### ISSUE THREAD

**Issue by holymonson** [polygamma/aurman#206]
## Description
Run `ssh XXX.XXX aurman -Syu --noconfirm`
```bash
~~ looking for new pkgbuilds and fetching them...
?? Do you want to see the changes of aurman? N/y: 2018-07-12 13:08:54,810 - main - main - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 842, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 750, in process
    package.show_pkgbuild(noedit, show_changes, pgp_fetch, keyserver, always_edit, default_show_changes)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1044, in show_pkgbuild
    default_show_changes):
  File "/usr/lib/python3.6/site-packages/aurman/utilities.py", line 239, in ask_user
    old_settings = termios.tcgetattr(fd)
termios.error: (25, 'Inappropriate ioctl for device')
```
## Possible Solution

Return `default ` in `ask_user()` directly when `--noconfirm` is set.

## Version of aurman you are using

2.16.2

**Comment by eli-schwartz** [comment]
You're missing `--noedit`.

Also sudo won't be able to prompt you for a password, but that's down to your system configuration...
