### ISSUE TITLE
Decoding problem while requesting AUR info

### ISSUE THREAD

**Issue by itsroot** [polygamma/aurman#272]
## Description

Aurman crushes during output of aurman -Ss android

## Expected Behavior

Expected output with list of android related packages of AUR.

## Current Behavior

It shows beginning of list and crushes with "2020-07-07 20:09:34,424 - aur_utilities - get_aur_info - ERROR - Decoding problem while requesting AUR info for "

Full output:

aurman -Ss android
extra/gvfs-mtp 1.44.1-3 (gnome) [installed]
    Virtual filesystem implementation for GIO (MTP backend; Android, media player)
community/android-file-transfer 3.9-1
    Android MTP client with minimalistic UI
community/android-tools 30.0.0-2 [installed]
    Android platform tools
community/android-udev 20200410-1 [installed]
    Udev rules to connect Android devices to your linux box
community/jadx 1.1.0-1
    Command line and GUI tools to produce Java source code from Android Dex and APK files
community/libgooglepinyin 0.1.2-4
    A fork from google pinyin on android
community/repo 2.7-1
    The Multiple Git Repository Tool from the Android Open Source Project
community/smali 2.3.4-1
    Assembler/disassembler for Android's dex format
community/ttf-droid 20121017-7.2
    General-purpose fonts released by Google as part of Android
2020-07-07 20:18:52,944 - aur_utilities - get_aur_info - ERROR - Decoding problem while requesting AUR info for ['android-x86-kirigami2', 'android-x86-zlib', 'flex-android', 'droidcam', 'android-coloredlogcat', 'android-x86-64-system-image-23', 'android-armv7a-eabi-fribidi', 'android-armv7a-eabi-system-image-18', 'android-google-apis-19', 'android-sdk-build-tools-24.0.3', 'genymotion', 'android-x86-x265', 'android-aarch64-kirigami2', 'marvin_dsc', 'numix-holo-themes', 'android-ndk-10e', 'android-emulator', 'android-ndk-beta', 'android-sdk-build-tools-18.1', 'android-armv7a-eabi-cppunit', 'android-armv7a-eabi-termcap', 'android-sdk-build-tools-20', 'android-samples-17', 'android-studio-canary', 'chromeos-apk-git', 'android-platform-dummy', 'flutter', 'android-sdk-build-tools-25.0.1', 'ttf-roboto-ibx', 'android-armv7a-eabi-speexdsp', 'android-apktool', 'android-sdk-cmdline-tools-latest', 'pidgin-pushbullet-git', 'android-sdk-build-tools-28', 'android-x86-system-image-19', 'xdroid-installer', 'android-google-apis-23', 'adbfs-git', 'python-adb', 'androidscreencast-bin', 'blink-server', 'android-sources-20', 'android-armv7a-eabi-x264', 'android-aarch64-boost', 'android-armv7a-eabi-libvpx', 'tuxjdk', 'android-armv7a-eabi-x265', 'android-sdk-build-tools-21.1.2', 'android-sdk-build-tools-17', 'android-x86-l-smash', 'android-sources-17', 'sndcpy-bin', 'android-x86-64-libssh', 'android-armv7a-eabi-system-image-14', 'python2-frida', 'android-platform-19', 'android-aarch64-opus', 'anbox-image-gapps-rooted', 'android-google-apis-15', 'android-x86-libxml2', 'pico-tts', 'eclipse-androidproguardscala', 'python-buildozer', 'sdat2img-git', 'android-platform', 'android-armv7a-eabi-system-image-23', 'drozer', 'android-armv7a-eabi-libxml2', 'android-sdk-build-tools-24.0.1', 'apkstudio-git', 'android-armv7a-eabi-libvorbis', 'flutter-beta', 'android-x86-64-libvorbis', 'notigo', 'android-aarch64-speex', 'android-armv7a-eabi-libwebp', 'android-armv7a-eabi-system-image-21', 'android-platform-29', 'fdk-aac-free', 'divvydroid-git', 'abootimg-git', 'noto-fonts-emoji-lollipop', 'unity-editor-beta-android', 'quark-engine', 'android-aarch64-libunistring', 'python2-androguard', 'android-sdk-cmake-3.6', 'android-sources-29', 'android-google-apis-x86-system-image-23', 'android-armv7a-eabi-libssh', 'android-sdk-build-tools-18.1.1', 'android-configure', 'android-x86-64-ffmpeg', 'cocos2d-x-src', 'android-x86-64-expat', 'android-x86-64-libogg', 'android-armv7a-eabi-system-image', 'android-armv7a-eabi-opus', 'android-x86-64-libpng', 'android-x86-64-system-image-29', 'android-sdk-build-tools-23', 'android-armv7a-eabi-libunistring', 'superbeam', 'android-google-apis-playstore-x86-64-system-image', 'android-sources-27', 'android-x86-lame', 'android-x86-64-system-image', 'android-platform-27', 'shashlik-bin', 'zenbound2', 'android-platform-26', 'android-sdk-build-tools-25.0.3', 'android-platform-22', 'android-tv-x86-system-image-22', 'fb-adb-git', 'android-x86-system-image-15', 'textto-bin', 'android-x86-expat', 'jmtpfs-git', 'android-simg2img', 'android-x86-libpng', 'android-sdk-build-tools', 'android-sources-22', 'android-x86-libiconv', 'android-google-apis-x86-system-image-29', 'android-x86-64-lcms2', 'android-samples-20', 'kde-thumbnailer-apk', 'carnet', 'android-x86-64-libxml2', 'python-android-backup-tools', 'schroot-droid', 'android-sources-28', 'android-sdk-build-tools-24.0.2', 'android-sdk-platform-tools', 'android-aarch64-libiconv', 'android-google-apis-x86-system-image', 'android-sdk-build-tools-21.0.1', 'android-sdk-platform-tools-dummy', 'bcm2079x-i2c', 'android-ndk-20b', 'logcat-color3', 'android-x86-64-opus', 'android-ndk-11c', 'arm-linux-gnueabihf-android-linux-api-headers', 'android-armv7a-eabi-zlib', 'android-armv7a-eabi-kirigami2', 'ormlite-android', 'android-armv7a-eabi-libtiff', 'owncloud-app-ocsms', 'vysor-git', 'android-x86-64-libtiff', 'jadx-bin', 'android-x86-libssh', 'android-ndk-16b', 'android-armv7a-eabi-speex', 'android-google-apis-x86-64-system-image-29', 'android-x86-64-system-image-22', 'python2-gcm', 'jadx-unstable-bin', 'remotelauncherserver-bin', 'android-platform-21', 'android-sdk-build-tools-27.0.2', 'android-platform-28', 'android-x86-speex', 'android-bash-completion', 'redex-git', 'android-x86-libunistring', 'v4l2loopback-dc-dkms', 'nextcloud-app-ocsms', 'fso-unbootimg', 'android-sdk-25.2.5', 'android-x86-speexdsp', 'android-google-apis-x86-64-22', 'android-platform-15', 'android-aarch64-termcap', 'android-armv7a-eabi-system-image-16', 'android-sdk-ndk-symlink', 'android-aarch64-fribidi', 'android-samples-18', 'android-x86-boost', 'android-apktool-git', 'android-x86-system-image-23', 'android-sdk-build-tools-23.0.3', 'sat-cagou-hg', 'android-x86-libvpx', 'android-aarch64-x264-bootstrap', 'web3j', 'android-google-apis-17', 'android-x86-64-fribidi', 'android-x86-system-image-17', 'ttf-droid-nonlatin-ib', 'android-sdk-build-tools-18.0.1', 'android-armv7a-eabi-expat', 'android-aarch64-libogg', 'android-sdk-build-tools-23.0.1', 'android-armv7a-eabi-giflib', 'android-aarch64-openssl', 'android-x86-64-libunistring', 'android-armv7a-eabi-lcms2', 'guiscrcpy', 'gnirehtet', 'android-ndk-19', 'vdr-vdrmanager', 'flutter-git', 'android-google-play-services', 'android-unpackbootimg', 'nodejs-airfile-git', 'linconnect-server-git', 'arm-eabi-4.8', 'ttf-droid-simple', 'android-google-apis-18', 'classyshark', 'simple-rt', 'android-sdk-build-tools-19.0.3', 'aio-remote', 'android-messages-desktop', 'android-studio-beta', 'anbox-image-houdini', 'libretro-px68k-git', 'android-meson', 'gvfs-mtp-git', 'android-sources-26', 'svox-pico-bin', 'python2-adb', 'an2linuxserver-git', 'tetherback', 'android-ndk-r18b', 'android-sdk-build-tools-19.1', 'sspl', 'android-aarch64-openjpeg2', 'archon-exec', 'android-x86-system-image-22', 'android-aarch64-libvpx', 'android-support-repository', 'android-sdk-build-tools-28.0.3', 'android-armv7a-eabi-system-image-20', 'android-aarch64-x265', 'android-sdk-build-tools-26.0.3', 'anbox-image-houdini-rooted', 'android-x86-64-lame', 'ttf-droid-ib', 'android-sdk-build-tools-21', 'raccoon', 'php-android-cli-git', 'android-x86-x264-bootstrap', 'jiri-git', 'android-x86-libogg', 'android-x86-64-libjpeg-turbo', 'android-sdk-build-tools-28.0.2', 'android-aarch64-x264', 'necta-wifi-mouse', 'android-platform-20', 'android-armv7a-eabi-xz', 'android-aarch64-libtheora', 'pidcat-git', 'apk-resigner', 'jadx-git', 'android-ndk-r17c', 'android-aarch64-libpng', 'android-armv7a-eabi-system-image-22', 'android-messages-desktop-bin', 'jsettlers-git', 'android-sdk-ant', 'android-x86-bzip2', 'flutter-dev', 'python-pyaxmlparser-git', 'android-x86-64-system-image-27', 'android-sdk-build-tools-28.0.1', 'android-aarch64-libvorbis', 'android-x86-opus', 'droidcam-dkms-git', 'android2po', 'python2-buildozer', 'qt5-qpa-hwcomposer-plugin', 'xamarin-android', 'inception-android', 'android-sdk-build-tools-27.0.1', 'android-x86-64-zlib', 'qt5-qpa-surfaceflinger-plugin', 'android-x86-64-libwebp', 'otf-literata', 'cargo-apk-git', 'apk-decompiler', 'android-udev-git', 'android-sdk-cmake', 'android-x86-ffmpeg', 'linuxsync-git', 'python-pyaxmlparser', 'android-sdk-build-tools-27', 'android-platform-16', 'mkbootfs', 'android-sdk-build-tools-25', 'android-armv7a-eabi-lame', 'android-sdk-build-tools-26', 'android-x86-termcap', 'android-x86-qt5', 'soundwire', 'mobydroid', 'android-sources-16', 'android-x86-64-xz', 'android-sdk-build-tools-23.0.2', 'android-x86-64-pcre', 'android-x86-64-x265', 'android-sources-24', 'android-x86-libtiff', 'dualbootpatcher-git', 'android-platform-14', 'android-docs', 'android-file-transfer-linux-git', 'rutorrent-mobile-git', 'dexpatcher', 'android-sdk-cmdline-tools-latest-dummy', 'android-x86-64-kirigami2', 'android-pkg-config', 'adb-sync-git', 'droidbot-git', 'gfxtablet-git', 'android-platform-17', 'android-aarch64-libjpeg-turbo', 'android-backup-extractor-git', 'android-x86-64-bzip2', 'android-x86-64-giflib', 'gplaycli', 'emacs-android-git', 'android-sources-18', 'pencil-android-lollipop-stencils-git', 'stf-git', 'adbcontrol', 'android-sdk-build-tools-27.0.3', 'smartcam', 'smali-git', 'android-sdk-build-tools-19', 'simg-tools', 'android-tools-git', 'android-sdk-build-tools-24', 'python-frida', 'android-cmake', 'android-ndk', 'android-support', 'android-aarch64-lcms2', 'android-aarch64-ffmpeg', 'hybris-ready', 'android-platform-24', 'stf', 'aafm-git', 'arm-eabi-4.7', 'android-armv7a-eabi-x264-bootstrap', 'python-adb-enhanced', 'android-sdk', 'python2-androguard-git', 'android-aarch64-xz', 'android-google-play-apk-expansion', 'android-armv7a-eabi-openssl', 'android-x86-64-l-smash', 'hybris-android-headers', 'android-sources-21', 'miraiok-bin', 'qemu-android-x86', 'mybackup', 'android-x86-libwebp', 'android-sdk-build-tools-29', 'raccoon-bin', 'logcat-colorize', 'android-armv7a-eabi-qt5', 'android-aarch64-pcre', 'scrcpy', 'devhub', 'android-x86-fribidi', 'qtadb', 'android-armv7a-eabi-pcre', 'android-x86-64-libiconv', 'android-x86-64-libtheora', 'python-androguard-git', 'android-google-repository', 'scrcpy-git', 'android-emulator-canary', 'aasdk-git', 'android-sdk-build-tools-22.0.1', 'arm-eabi-4.6', 'android-sdk-build-tools-dummy', 'android-platform-23', 'android-platform-13', 'android-google-apis-playstore-x86-64-system-image-29', 'anbox-image-gapps', 'fastlane', 'adbfs-rootless-git', 'android-sources-23', 'android-studio-dummy', 'android-x86-64-x264', 'android-studio-launcher', 'svg2vd', 'android-x86-openssl', 'sevensquare-git', 'rofication-git', 'xamarin-android-git', 'anbox-git', 'android-x86-openjpeg2', 'android-armv7a-eabi-system-image-19', 'android-armv7a-eabi-l-smash', 'android-aarch64-zlib', 'android-sdk-build-tools-29.0.2', 'android-emulator-dummy', 'android-x86-64-speexdsp', 'archdroid-icon-theme', 'sidequest-bin', 'android-sources', 'bootimg-tools-git', 'android-armv7a-eabi-system-image-15', 'android-ndk-14b', 'archdroid-icon-theme-git', 'android-x86-x264', 'anbox-image', 'android-x86-xz', 'libcamera-git', 'android-x86-libtheora', 'android-aarch64-bzip2', 'guiscrcpy-git', 'android-google-apis-x86-64-system-image', 'android-auto-api-simulators', 'android-sdk-build-tools-26.0.1', 'android-x86-64-termcap', 'hybris-usb', 'android-aarch64-lame', 'android-aarch64-expat', 'android-sdk-build-tools-22', 'android-armv7a-eabi-openjpeg2', 'android-aarch64-cppunit', 'android-sdk-build-tools-19.0.1', 'cloud-print-connector-git', 'android-sdk-build-tools-19.0.2', 'android-x86-pcre', 'android-armv7a-eabi-ffmpeg', 'armm', 'gmote-server', 'android-x86-64-openssl', 'fissh', 'nextcloud-app-ocsms-git', 'android-aarch64-libxml2', 'qt-scrcpy', 'apk2gold-git', 'android-x86-64-speex', 'android-x86-64-boost', 'android-sdk-build-tools-21.1', 'dex2jar-git', 'img2sdat-git', 'android-armv7a-eabi-libjpeg-turbo', 'python-p4a-build', 'index-fm-git', 'android-x86-libvorbis', 'android-aarch64-libssh', 'android-x86-64-qt5', 'android-sdk-build-tools-26.0.2', 'android-armv7a-eabi-libiconv', 'android-aarch64-l-smash', 'android-google-apis-16', 'genymotion-beta', 'android-google-apis', 'dex2jar', 'android-x86-64-libvpx', 'android-x86-libjpeg-turbo', 'android-constraint-layout', 'eclipse-android', 'android-platform-25', 'android-x86-64-x264-bootstrap', 'android-studio', 'opensesame', 'android-tv-armv7a-eabi-system-image-22', 'anbox-modules-dkms-git', 'unity-editor-lts-android', 'aosp-devel', 'bubbleupnpserver', 'android-x86-64-system-image-24', 'android-x86-64-openjpeg2', 'adb-screen-tools', 'android-samples-19', 'android-armv7a-eabi-libtheora', 'bootimgtool-git', 'android-samples-16', 'android-google-apis-armv7a-eabi', 'android-armv7a-eabi-libpng', 'openauto-git', 'android-sdk-build-tools-29.0.3', 'android-aarch64-qt5', 'android-cmake-git', 'android-x86-64-system-image-28', 'redex', 'android-google-apis-21', 'android-armv7a-eabi-boost', 'navitconfigurator-git', 'android-aarch64-giflib', 'android-platform-18', 'python2-p4a-build', 'android-google-apis-playstore-x86-system-image', 'android-armv7a-eabi-libogg', 'droidcam-dkms', 'gvfs-mtp-nosystemd', 'usbaudio-git', 'bundletool', 'python-pushnotify', 'mobac', 'android-environment', 'android-ndk-13b', 'android-armv7a-eabi-bzip2', 'android-sources-19', 'android-aarch64-speexdsp', 'android-google-play-licensing', 'python-androguard', 'android-sdk-build-tools-25.0.2', 'android-sdk-dummy', 'android-dumpkey', 'android-x86-giflib', 'archon', 'vysor-appimage', 'android-platform-30', 'android-x86-system-image', 'android-sdk-build-tools-29.0.1', 'unity-editor-android', 'android-armv7a-eabi-system-image-17', 'android-sdk-build-tools-30', 'android-aarch64-libtiff', 'android-aarch64-libwebp', 'android-x86-lcms2']
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aurman/aur_utilities.py", line 50, in get_aur_info
    json.loads(
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

## Version of `aurman` you are using

aurman -V
:: 2.19.1-1

## Content of `aurman` config

my ~/.config/aurman/aurman_config  is empty

## Steps to Reproduce

1. Run aurman -Ss android

## Read the README

I read

## Running linux distribution

Manjaro linux, I dont think this issue is distrib related.

**Comment by eli-schwartz** [comment]
Not handling HTTP 414 correctly, also not splitting properly.

debug printing:

`for:  https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pico-tts&arg[]=aasdk-git&arg[]=android-aarch64-libogg&arg[]=android-google-apis-x86-system-image&arg[]=php-android-cli-git&arg[]=qemu-android-x86&arg[]=smali-git&arg[]=drozer&arg[]=anbox-image-gapps-rooted&arg[]=eclipse-androidproguardscala&arg[]=android-x86-64-libiconv&arg[]=android-sdk-ndk-symlink&arg[]=android-studio-canary&arg[]=android-armv7a-eabi-qt5&arg[]=arm-eabi-4.6&arg[]=hybris-android-headers&arg[]=android-x86-libssh&arg[]=apk2gold-git&arg[]=android-sdk-build-tools-27.0.2&arg[]=hybris-ready&arg[]=android-sdk-build-tools-29.0.2&arg[]=otf-literata&arg[]=svg2vd&arg[]=android-platform-13&arg[]=android-google-repository&arg[]=android-x86-64-system-image-23&arg[]=android-platform-21&arg[]=android-ndk-11c&arg[]=python-pyaxmlparser&arg[]=android-google-play-licensing&arg[]=ttf-droid-simple&arg[]=android-sdk-build-tools-18.0.1&arg[]=android-armv7a-eabi-pcre&arg[]=android-cmake&arg[]=android-samples-18&arg[]=android-sdk-build-tools-27.0.1&arg[]=android-emulator-dummy&arg[]=android-platform-26&arg[]=simg-tools&arg[]=android-google-apis-19&arg[]=androidscreencast-bin&arg[]=android-google-apis-17&arg[]=android-aarch64-pcre&arg[]=android-x86-64-libunistring&arg[]=android-x86-termcap&arg[]=android-aarch64-speex&arg[]=android-x86-libiconv&arg[]=android-google-play-services&arg[]=android-armv7a-eabi-cppunit&arg[]=android-x86-64-x264-bootstrap&arg[]=anbox-image-houdini-rooted&arg[]=android-sdk-build-tools-18.1.1&arg[]=python2-buildozer&arg[]=android-x86-64-openssl&arg[]=jadx-bin&arg[]=android-armv7a-eabi-system-image-20&arg[]=android-platform-dummy&arg[]=android-x86-64-libtheora&arg[]=android-sdk-build-tools-19&arg[]=android-x86-64-fribidi&arg[]=android-x86-64-expat&arg[]=android-samples-17&arg[]=android-platform-24&arg[]=android-udev-git&arg[]=android-x86-x264&arg[]=python-frida&arg[]=dex2jar&arg[]=android-armv7a-eabi-libiconv&arg[]=ttf-droid-nonlatin-ib&arg[]=android-x86-64-l-smash&arg[]=blink-server&arg[]=android-sdk-build-tools-26.0.1&arg[]=android-armv7a-eabi-libssh&arg[]=android-unpackbootimg&arg[]=android-x86-64-boost&arg[]=android-x86-64-x265&arg[]=arm-eabi-4.8&arg[]=android-sdk-platform-tools-dummy&arg[]=zenbound2&arg[]=android-sources-18&arg[]=android-platform-14&arg[]=android-sources-26&arg[]=simple-rt&arg[]=android-platform-29&arg[]=flutter-beta&arg[]=android-x86-64-ffmpeg&arg[]=android-x86-lame&arg[]=flutter-git&arg[]=tetherback&arg[]=adbfs-git&arg[]=android-aarch64-l-smash&arg[]=android-x86-64-qt5&arg[]=android-sdk-platform-tools&arg[]=svox-pico-bin&arg[]=android-x86-pcre&arg[]=redex&arg[]=android-sources-23&arg[]=linuxsync-git&arg[]=anbox-image&arg[]=android-x86-libwebp&arg[]=android-google-apis-x86-64-22&arg[]=android-armv7a-eabi-libvorbis&arg[]=dex2jar-git&arg[]=xdroid-installer&arg[]=android-messages-desktop&arg[]=android-sdk-build-tools-19.0.2&arg[]=python-androguard-git&arg[]=android-x86-xz&arg[]=android-armv7a-eabi-bzip2&arg[]=notigo&arg[]=android-x86-64-zlib&arg[]=android-x86-64-lcms2&arg[]=rofication-git&arg[]=android-armv7a-eabi-x264-bootstrap&arg[]=android-aarch64-cppunit&arg[]=android-sources-19&arg[]=pidgin-pushbullet-git&arg[]=android-ndk-16b&arg[]=python-android-backup-tools&arg[]=android-ndk-beta&arg[]=openauto-git&arg[]=android-aarch64-fribidi&arg[]=android-armv7a-eabi-kirigami2&arg[]=qt5-qpa-surfaceflinger-plugin&arg[]=android-aarch64-boost&arg[]=android-sdk-build-tools-24.0.1&arg[]=stf&arg[]=android-google-apis-18&arg[]=android-x86-system-image-23&arg[]=android-aarch64-x264&arg[]=libretro-px68k-git&arg[]=android-armv7a-eabi-x264&arg[]=inception-android&arg[]=ormlite-android&arg[]=archon-exec&arg[]=stf-git&arg[]=android-platform-20&arg[]=bubbleupnpserver&arg[]=android-armv7a-eabi-system-image-23&arg[]=android-armv7a-eabi-system-image-16&arg[]=jiri-git&arg[]=android-google-play-apk-expansion&arg[]=android-armv7a-eabi-libxml2&arg[]=android-armv7a-eabi-libunistring&arg[]=android-sources&arg[]=android-x86-64-libtiff&arg[]=android-sdk-build-tools-23.0.3&arg[]=redex-git&arg[]=android-x86-system-image-15&arg[]=fissh&arg[]=usbaudio-git&arg[]=flutter-dev&arg[]=android-x86-libvpx&arg[]=qt5-qpa-hwcomposer-plugin&arg[]=tuxjdk&arg[]=android-sdk&arg[]=android-sdk-build-tools&arg[]=android-sdk-cmake-3.6&arg[]=android-armv7a-eabi-system-image-21&arg[]=armm&arg[]=android-sdk-build-tools-29.0.1&arg[]=android-sdk-build-tools-19.1&arg[]=nextcloud-app-ocsms-git&arg[]=android-google-apis-21&arg[]=android-sdk-build-tools-21.1&arg[]=android-x86-libjpeg-turbo&arg[]=an2linuxserver-git&arg[]=android-aarch64-libvorbis&arg[]=android-sources-29&arg[]=archdroid-icon-theme&arg[]=android-aarch64-libtheora&arg[]=android-x86-speex&arg[]=python2-gcm&arg[]=android-aarch64-openssl&arg[]=aio-remote&arg[]=sdat2img-git&arg[]=android-aarch64-libjpeg-turbo&arg[]=android-studio&arg[]=android-google-apis-x86-64-system-image&arg[]=android-samples-16&arg[]=scrcpy-git&arg[]=android-sources-17&arg[]=smartcam&arg[]=jmtpfs-git&arg[]=android-armv7a-eabi-libtheora&arg[]=android-x86-64-kirigami2&arg[]=android-armv7a-eabi-system-image-18&arg[]=android-armv7a-eabi-speexdsp&arg[]=android-sdk-build-tools-18.1&arg[]=android-sdk-build-tools-26.0.3&arg[]=android-armv7a-eabi-boost&arg[]=logcat-colorize&arg[]=android-ndk-14b&arg[]=xamarin-android&arg[]=android-armv7a-eabi-xz&arg[]=gvfs-mtp-git&arg[]=android-platform-17&arg[]=v4l2loopback-dc-dkms&arg[]=android-aarch64-libpng&arg[]=android-armv7a-eabi-system-image&arg[]=marvin_dsc&arg[]=android-x86-x265&arg[]=android-file-transfer-linux-git&arg[]=android-ndk-20b&arg[]=android-ndk&arg[]=android-x86-libvorbis&arg[]=shashlik-bin&arg[]=unity-editor-android&arg[]=android-auto-api-simulators&arg[]=remotelauncherserver-bin&arg[]=android-x86-openjpeg2&arg[]=guiscrcpy&arg[]=android-x86-64-opus&arg[]=android-armv7a-eabi-x265&arg[]=android-x86-libpng&arg[]=android-aarch64-kirigami2&arg[]=necta-wifi-mouse&arg[]=ttf-droid-ib&arg[]=android-configure&arg[]=anbox-git&arg[]=android-x86-64-system-image-27&arg[]=python2-p4a-build&arg[]=android-x86-libxml2&arg[]=android-x86-giflib&arg[]=aafm-git&arg[]=android-platform-25&arg[]=python-adb&arg[]=android-x86-64-libjpeg-turbo&arg[]=android-x86-expat&arg[]=nodejs-airfile-git&arg[]=android-aarch64-termcap&arg[]=cocos2d-x-src&arg[]=android-x86-64-x264&arg[]=index-fm-git&arg[]=droidcam-dkms&arg[]=fastlane&arg[]=android-apktool&arg[]=android-cmake-git&arg[]=android-armv7a-eabi-system-image-19&arg[]=android-x86-kirigami2&arg[]=android-x86-system-image-17&arg[]=dualbootpatcher-git&arg[]=android-sdk-cmake&arg[]=android-x86-64-termcap&arg[]=android-sdk-build-tools-24&arg[]=bootimgtool-git&arg[]=android-platform-15&arg[]=android-x86-64-libwebp&arg[]=android-armv7a-eabi-ffmpeg&arg[]=android-samples-19&arg[]=qt-scrcpy&arg[]=img2sdat-git&arg[]=adb-sync-git&arg[]=android-docs&arg[]=android-x86-x264-bootstrap&arg[]=android-platform&arg[]=abootimg-git&arg[]=cargo-apk-git&arg[]=bundletool&arg[]=android-x86-64-system-image-29&arg[]=android-x86-system-image-19&arg[]=android-armv7a-eabi-lame&arg[]=android-x86-64-libssh&arg[]=android-x86-libunistring&arg[]=vdr-vdrmanager&arg[]=gplaycli&arg[]=android-sdk-25.2.5&arg[]=android-aarch64-qt5&arg[]=genymotion&arg[]=libcamera-git&arg[]=android-platform-30&arg[]=android-armv7a-eabi-l-smash&arg[]=android-bash-completion&arg[]=apk-decompiler&arg[]=anbox-modules-dkms-git&arg[]=genymotion-beta&arg[]=android-sdk-dummy&arg[]=android-armv7a-eabi-speex&arg[]=android-sdk-build-tools-19.0.3&arg[]=quark-engine&arg[]=jsettlers-git&arg[]=logcat-color3&arg[]=vysor-appimage&arg[]=android-sdk-build-tools-25&arg[]=android-google-apis-playstore-x86-64-system-image-29&arg[]=android-aarch64-libxml2&arg[]=android-x86-openssl&arg[]=android-x86-64-pcre&arg[]=sevensquare-git&arg[]=android-x86-speexdsp&arg[]=android-x86-boost&arg[]=android-sdk-build-tools-22&arg[]=sidequest-bin&arg[]=mkbootfs&arg[]=python-pyaxmlparser-git&arg[]=android-sdk-build-tools-21.0.1&arg[]=jadx-git&arg[]=numix-holo-themes&arg[]=android-armv7a-eabi-openssl&arg[]=android-aarch64-zlib , response:  414`

**Comment by polygamma** [comment]
There are still `aurman` users alive besides me? Crazy!

Going to look into this, maybe I should look into https://github.com/polygamma/aurman/pull/269 first?

And where is my GPG key...

**Comment by laloch** [comment]
> There are still `aurman` users alive besides me? Crazy!

Of course there are! The last time I checked, `aurman` was still the best AUR helper around (or at least the one that suites me the best). Thank you!

**Comment by polygamma** [comment]
@itsroot I have released `aurman` 2.20, please check if everything works as intended now

**Comment by aptinio** [comment]
Another `aurman` user here. I can confirm that `aurman -Ss` with v2.20.1. Thanks for maintaining and sharing `aurman`! :heart:
