### ISSUE TITLE
Error parsing pacman.conf

### ISSUE THREAD

**Issue by ypnos** [polygamma/aurman#47]
Aurman seems to have problems with bash comments in pacman.conf.

I get the following error:
```
2018-03-26 11:13:09,359 - main - main - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 517, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 290, in process
    upstream_system = System(System.get_repo_packages())
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1183, in get_repo_packages
    return Package.get_packages_from_expac("-S", (), PossibleTypes.REPO_PACKAGE)
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 262, in get_packages_from_expac
    repos = Package.get_known_repos()
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 240, in get_known_repos
    return [db.name for db in PacmanConfig(conf="/etc/pacman.conf").initialize_alpm().get_syncdbs()]
  File "/usr/lib/python3.6/site-packages/pycman/config.py", line 160, in __init__
    self.load_from_file(conf)
  File "/usr/lib/python3.6/site-packages/pycman/config.py", line 165, in load_from_file
    for section, key, value in pacman_conf_enumerator(filename):
  File "/usr/lib/python3.6/site-packages/pycman/config.py", line 119, in pacman_conf_enumerator
    raise InvalidSyntax(f.name, 'invalid key for repository configuration', line)
pycman.config.InvalidSyntax: unable to parse /etc/pacman.conf, invalid key for repository configuration: '[ownstuff] # mingw32-64 packages'
```

The error does not occur if I place that comment above the `[ownstuff]` line.

**Comment by polygamma** [comment]
No aurman error, you must not put comments into that line.

**Comment by AladW** [comment]
That syntax is still valid to pacman, right? Is this some pyalpm limitation (last I checked it painfully parses pacman configuration by hand) or do you use your own parser?

**Comment by ypnos** [comment]
Have a look at https://bugs.archlinux.org/task/41412

**Comment by AladW** [comment]
I would suggest to open an issue for pyalpm for it to use `pacman-conf` (added to pacman master branch, see https://git.archlinux.org/pacman.git/commit/?id=170bb80a1f8a020595738c7febdb15c68574ce29)

**Comment by polygamma** [comment]
I am using pyalpm for parsing of pacman.conf, I am not touching that by myself
