### ISSUE TITLE
Providers not taken into account in deps solver

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#5]
I have `cower-git` installed, which provides `cower`.
When installing a package that requires `cower`, the dependency solver fails.

In addition to package names, you'll need to check providers here.

```
$ python main.py -S --packages pacaur-git
2018-02-08 12:26:47,693 - package_utilites - check_versioning_and_conflicts - ERROR - Dep cower not fulfilled
2018-02-08 12:26:47,694 - main - process - ERROR - Dep problem, exiting.
2018-02-08 12:26:47,694 - main - <module> - ERROR - Unknown exception occurred.
Traceback (most recent call last):
  File "main.py", line 112, in process
    check_versioning_and_conflicts(packages_going_to_install, classified_packages)
  File "/home/remy/code/aurman/src/package_utilites.py", line 319, in check_versioning_and_conflicts
    raise InvalidInput()
own_exceptions.InvalidInput

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 167, in <module>
    process(argv[1:])
  File "main.py", line 115, in process
    exit(1)
SystemExit: 1
```

**Comment by polygamma** [comment]
fixed in: https://github.com/polygamma/aurman/commit/8866ed0da2429d05f439d17805f92d5b2b8dd6ce

not a nice fix, but a nice solution is being implemented in the next rewrite
