### ISSUE TITLE
aurman -V

### ISSUE THREAD

**Issue by mihjok** [polygamma/aurman#51]
Should it behave this way?

> $ aurman --version
2018-04-02 18:17:01,419 - wrappers - expac - ERROR - expac query expac -Q '%v' aurman-git failed
2018-04-02 18:17:01,419 - main - main - ERROR - 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 517, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 55, in process
    aurman_note(expac("-Q", ("v",), ("aurman-git",))[0])
  File "/usr/lib/python3.6/site-packages/aurman/wrappers.py", line 72, in expac
    raise InvalidInput("expac query {} failed".format(query))
aurman.own_exceptions.InvalidInput: expac query expac -Q '%v' aurman-git failed

**Comment by polygamma** [comment]
i cannot reproduce that:
```
[jonny@jonny-arch-pc ~]$ aurman --version
:: 2.9.18.r0.g51298fe-1
```

**Comment by polygamma** [comment]
ahhhh.... i know what's wrong... will be fixed

**Comment by polygamma** [comment]
done.

**Comment by mihjok** [comment]
Congrats. You are fast :+1:
