### ISSUE TITLE
Distribution not found

### ISSUE THREAD

**Issue by lumpiluk** [polygamma/aurman#52]
After the most recent update (2.9.19) I'm getting the following when I try to run aurman:

```
Traceback (most recent call last):
  File "/usr/bin/aurman", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'requests' distribution was not found and is required by aurman
```

A recent install (possibly ros-kinetic) may have set python2 as the default. I have reset the symlink /usr/bin/python back to python3 and `python --version` now is back to 3.6.4, but the above error persists. Maybe main.py needs a shebang?

**Comment by lumpiluk** [comment]
Sorry, never mind, I just checked the contents of `/usr/bin/aurman`. Somehow it got the shebang `#1/opt/ros/kinetic/bin/python`, which is of course the wrong python.

**Comment by polygamma** [comment]
You got the wrong shebang because you built the aurman package with the wrong python version. The shebang is added during execution of the setup.py, hence rebuilding the whole package should fix your problem

**Comment by polygamma** [comment]
I am nevertheless going to add the needed python version to the setup.py with the next aurman update

**Comment by polygamma** [comment]
done: https://github.com/polygamma/aurman/commit/f5cf6a2494fabee909b5802f2effd3151cc038c0
