### ISSUE TITLE
Error when aborting on main prompt

### ISSUE THREAD

**Issue by rmarquis** [polygamma/aurman#6]
On 0.33.3:

```
$ python main.py -S --packages pacaur-git
AUR Packages: pacaur-git
Repo Packages:
Do you want to install these packages? Y/n: n
2018-02-08 12:46:51,918 - main - <module> - ERROR - Unknown exception occurred.
Traceback (most recent call last):
  File "main.py", line 167, in <module>
    process(argv[1:])
  File "main.py", line 123, in process
    exit(1)
SystemExit: 1
```

**Comment by polygamma** [comment]
"fixed" in: https://github.com/polygamma/aurman/commit/d036f8f60b5057a47d555e8f06c5b6b3e3dfa9c8
