### ISSUE TITLE
 raise InvalidInput("makepkg query {} failed".format(makepkg_query))

### ISSUE THREAD

**Issue by Enverex** [polygamma/aurman#63]
Trying to build lib32-ffmpeg (which currently doesn't build anyway, but that's not aurman's fault) causes aurman to crash out:

```
==> Validating source files with sha256sums...
    ffmpeg-3.4.2.tar.bz2 ... Passed
    ffmpeg-3.4.2.tar.bz2.asc ... Skipped
==> Verifying source file signatures with gpg...
    ffmpeg-3.4.2.tar.bz2 ... Passed
==> Extracting sources...
  -> Extracting ffmpeg-3.4.2.tar.bz2 with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
ERROR: gnutls not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
==> ERROR: A failure occurred in build().
    Aborting...
2018-04-10 15:01:11,914 - wrappers - makepkg - ERROR - makepkg query makepkg -cf --noconfirm failed
2018-04-10 15:01:11,914 - main - main - ERROR -
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 517, in main
    process(argv[1:])
  File "/usr/lib/python3.6/site-packages/aurman/main.py", line 497, in process
    package.build()
  File "/usr/lib/python3.6/site-packages/aurman/classes.py", line 1102, in build
    makepkg("-cf --noconfirm", False, package_dir)
  File "/usr/lib/python3.6/site-packages/aurman/wrappers.py", line 140, in makepkg
    raise InvalidInput("makepkg query {} failed".format(makepkg_query))
aurman.own_exceptions.InvalidInput: makepkg query makepkg -cf --noconfirm failed
```

Obviously the expected result is for it to catch the issue, rather than Python spewing out a traceback.

**Comment by polygamma** [comment]
Will be changed

**Comment by polygamma** [comment]
see: https://github.com/polygamma/aurman/commit/65a0729c94423e24daedf1fbf5b50c851cd5abd8
